{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openaikit\/apierrordetail\/message"]}],"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","modules":[{"name":"OpenAIKit"}],"role":"symbol","title":"message","externalID":"s:9OpenAIKit14APIErrorDetailV7messageSSvp","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/APIErrorDetail\/message"},"hierarchy":{"paths":[["doc:\/\/OpenAIKit\/documentation\/OpenAIKit","doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/APIErrorDetail"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["Linux"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This message provides a clear description of what went wrong","type":"text"},{"text":" ","type":"text"},{"text":"and often includes suggestions for how to fix the issue.","type":"text"}]},{"anchor":"Examples","type":"heading","level":2,"text":"Examples"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"“Invalid API key provided”"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"“Rate limit exceeded for requests”"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"“The model ","type":"text"},{"type":"codeVoice","code":"gpt-4"},{"text":" does not exist”","type":"text"}]}]}]}],"kind":"content"}],"abstract":[{"type":"text","text":"The human-readable error message."}],"references":{"doc://OpenAIKit/documentation/OpenAIKit/APIErrorDetail":{"url":"\/documentation\/openaikit\/apierrordetail","abstract":[{"text":"Detailed error information from the OpenAI API.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"APIErrorDetail"}],"type":"topic","title":"APIErrorDetail","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIErrorDetail"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/APIErrorDetail"},"doc://OpenAIKit/documentation/OpenAIKit/APIErrorDetail/message":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/openaikit\/apierrordetail\/message","abstract":[{"text":"The human-readable error message.","type":"text"}],"title":"message","identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/APIErrorDetail\/message"},"doc://OpenAIKit/documentation/OpenAIKit":{"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/openaikit","abstract":[{"text":"A powerful, type-safe Swift SDK for the OpenAI API with support for all major endpoints and platforms.","type":"text"}],"title":"OpenAIKit","identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit"}}}